export const schema = [
	['name', ''],
	['level', 1],
	['actionPoints', 0],
	['saves', 0],
	['size', 'Medium'],
	['role', 'Skirmisher'],
	['variant', 'Normal'],
	['origin', 'Natural'],
	['type', 'Humanoid'],
	['keywords', ''],
	['reflexes', 'Normal'],
	['fortitude', 'Normal'],
	['will', 'Normal'],
	['speed', '6'],
	['senses', ''],
	['aura', ''],
	['immune', ''],
	['resist', ''],
	['vulnerable', ''],
	['hp', 0],
	['bloodied', 0],
	['ac', 0],
	['fort', 0],
	['ref', 0],
	['will', 0],
	['strength', 12],
	['constitution', 12],
	['dexterity', 12],
	['intelligence', 12],
	['wisdom', 12],
	['charisma', 12],
	['skills', []],
	['languages', []],
	['alignment', ''],
	['token', null],
	[
		'powers',
		[
			{
				name: 'Melee Basic Attack',
				range: 'Melee',
				'range-Range': 1,
				usage: 'At-Will',
			},
		],
	],
];
